### ISSUE TITLE
Broken link to the description of IBC protocol

### ISSUE THREAD

**Issue by BlackPanthar** [cosmos/v1.cosmos.network#209]
Hello! Just wanted to give everyone a heads up. It looks like the links to the IBC specification are broken. This is at https://v1.cosmos.network/intro under "How IBC works" / "Validator"

Goes to:
https://github.com/cosmos/cosmos-sdk/tree/master/docs/spec/ibc

I think it Should be (Please confirm):
https://github.com/cosmos/cosmos-sdk/tree/master/docs/ibc

**Comment by barriebyron** [comment]
Hi, Ezekiel (I am digging your GitHub @BlackPanthar handle) thanks so much for letting us know that the very important IBC link isn't working! 
Looks like someone else noticed the previous link was broken https://github.com/cosmos/cosmos-sdk/pull/9715/files 

Hmmm we can rephrase the descriptive link text 

> For a more comprehensive description of the IBC protocol, you can look at _this specification_.

so that we don't send our readers to "this specification" and go instead to the docs where you suggest, but let's send the reader to the published docs at https://docs.cosmos.network/master/ibc/overview.html

**Comment by barriebyron** [comment]
Now you inspired me to verify all of the links on that page. !oof! the "this spec" link
in the PROBABILISTIC-FINALITY CHAINS section is also busted:

> If you want to learn more about Peg-Zones you can take a look at [this spec](https://github.com/cosmos/gravity-bridge/tree/master/spec).

In this Peg-Zones case, we can just omit that last sentence since the content has links to a blog post and the Gravity Bridge repo.

**Comment by BlackPanthar** [comment]
Thanks Barrie
